### ISSUE TITLE
Py2exe error ImportError: cannot import name 'UpdateResources'

### ISSUE THREAD

**Issue by sumeshgopu** [twilio/twilio-python#206]
I wrote a small desktop application on Pyqt4 and pyhton 3.4 , When I compile it to exe using py2exe 0.9.22 I get the below error, Can someone help me , I am new to Github also

Traceback (most recent call last):
  File "C:\Python34\Scripts\build_exe-script.py", line 9, in <module>
    load_entry_point('py2exe==0.9.2.2', 'console_scripts', 'build_exe')()
  File "C:\Python34\lib\site-packages\pkg_resources.py", line 353, in load_entry
_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python34\lib\site-packages\pkg_resources.py", line 2302, in load_entr
y_point
    return ep.load()
  File "C:\Python34\lib\site-packages\pkg_resources.py", line 2029, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "c:\python34\lib\site-packages\py2exe\__init__.py", line 9, in <module>
    patch_distutils()
  File "c:\python34\lib\site-packages\py2exe\patch_distutils.py", line 68, in pa
tch_distutils
    from . import distutils_buildexe
  File "c:\python34\lib\site-packages\py2exe\distutils_buildexe.py", line 91, in
 <module>
    from . import runtime
  File "c:\python34\lib\site-packages\py2exe\runtime.py", line 16, in <module>
    from .resources import UpdateResources
ImportError: cannot import name 'UpdateResources'

**Comment by carlosdp** [comment]
This seems like a Py2exe issue, I would ask on their issues/forums if you still have this problem!
