### ISSUE TITLE
'ClientCapabilityToken' object has no attribute 'generate'

### ISSUE THREAD

**Issue by riturajtiwari** [twilio/twilio-python#454]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**Version:**
6.24.0
### Code Snippet
From starter samples provided under [https://github.com/TwilioDevEd/browser-calls-flask](https://github.com/TwilioDevEd/browser-calls-flask)
```python
@app.route('/support/token', methods=['GET'])
def get_token():
    """Returns a Twilio Client token"""
    # Create a TwilioCapability object with our Twilio API credentials
    capability = ClientCapabilityToken(
        app.config['TWILIO_ACCOUNT_SID'],
        app.config['TWILIO_AUTH_TOKEN'])

    # Allow our users to make outgoing calls with Twilio Client
    capability.allow_client_outgoing(app.config['TWIML_APPLICATION_SID'])

    # If the user is on the support dashboard page, we allow them to accept
    # incoming calls to "support_agent"
    # (in a real app we would also require the user to be authenticated)
    if request.args.get('forPage') == '/dashboard':
        capability.allow_client_incoming('support_agent')
    else:
        # Otherwise we give them a name of "customer"
        capability.allow_client_incoming('customer')

    # Generate the capability token
    token = capability.generate()
    # token = capability.to_jwt()
    # token = capability.payload

    return jsonify({'token': token})
```

### Exception/Log
```
Traceback (most recent call last):
  File "/path/to/PythonVirtualEnvs/browser-calls-flask/lib/python3.6/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/path/to/PythonVirtualEnvs/browser-calls-flask/lib/python3.6/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/path/to/PythonVirtualEnvs/browser-calls-flask/lib/python3.6/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/path/to/PythonVirtualEnvs/browser-calls-flask/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/path/to/PythonVirtualEnvs/browser-calls-flask/lib/python3.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/path/to/PythonVirtualEnvs/browser-calls-flask/lib/python3.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/path/to/PythonVirtualEnvs/browser-calls-flask/lib/python3.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/path/to/PythonVirtualEnvs/browser-calls-flask/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/path/to/PythonVirtualEnvs/browser-calls-flask/lib/python3.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/path/to/PythonVirtualEnvs/browser-calls-flask/lib/python3.6/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/path/to/Development/browser-calls-flask/browser_calls_flask/views.py", line 58, in get_token
    token = capability.generate()
AttributeError: 'ClientCapabilityToken' object has no attribute 'generate'
```

### Steps to Reproduce
Follow the steps in the quick start guide located at [https://github.com/TwilioDevEd/browser-calls-flask](https://github.com/TwilioDevEd/browser-calls-flask)

I have also tried changing the code to use `capability.to_jwt()` and `capability.payload` but the resulting tokens cause other failures.

**Comment by riturajtiwari** [comment]
This was fixed by changing the code in the browser-calls-flask sample. [See pull request](https://github.com/TwilioDevEd/browser-calls-flask/pull/11).
