### ISSUE TITLE
How could twilio responde google sheet data as pandas dataframe

### ISSUE THREAD

**Issue by lidatou1991** [twilio/twilio-python#468]
I am trying to use twilio to fetch my google sheet data via pygsheet. I have tested the pygsheet part code and it could returns google sheet content as dataframe. I have also tested the basic configuration is Ok since I can receive simple text response from twilio.

The problem is that I do not know how to embed the pandas dataframe into the `TwiML` response body. According to the log, it is caused by the `messaging_response.py` line 76:

```
if body:
```

as the body I want to responde is a pandas dateframe object, so it gives the error.
**Version:**
python 3.6
### Code Snippet
```python
# /usr/bin/env python
# Download the twilio-python library from twilio.com/docs/libraries/python
# -*- coding: utf-8 -*-
from flask import Flask, request
from twilio.twiml.messaging_response import MessagingResponse

import pygsheets
import socket
import socks
import pandas


app = Flask(__name__)

@app.route("/sms", methods=['GET', 'POST'])
def send_sms():
    #get the imcoing message
    msg = request.values.get("Body").lower() # convert to lowercase

    #set proxy
    socket.setdefaulttimeout(150)
    socks.set_default_proxy(socks.SOCKS5, "127.0.0.1", 1086)
    socket.socket = socks.socksocket

    #login to google authorize
    from oauth2client.service_account import ServiceAccountCredentials

    gc = pygsheets.authorize(client_secret='client_secret.json')

    wks = gc.open("test").sheet1
    df = wks.get_as_df()
    col_name = str(msg)
    ret = df['column1']

    """Respond to incoming messages with a friendly SMS."""
    # Start our response
    resp = MessagingResponse()

    # Add a message
    resp.message(ret)

    return str(ret)

if __name__ == "__main__":
    app.run(debug=True)

```

### Exception/Log
```
Traceback (most recent call last):
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/limao/Documents/gstwilio/run.py", line 40, in send_sms
    resp.message(df)
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/twilio/twiml/messaging_response.py", line 45, in message
    **kwargs
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/twilio/twiml/messaging_response.py", line 76, in __init__
    if body:
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 1576, in __nonzero__
    .format(self.__class__.__name__))
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

### Steps to Reproduce
1. run the code above
2. find the error log

### Feature Request
I am wondering is there any any to embed pandas dataframe into the response body.

**Comment by childish-sambino** [comment]
I'm not sure what the data type is for your column (`ret = df[col_name]`) but it needs to be converted to a string or a dict in order to add it as the message body. I would start by inspecting the column types from your document and how to properly serialize them.

Also, the last line should be `return str(resp)`.

**Comment by lidatou1991** [comment]
> I'm not sure what the data type is for your column (`ret = df[col_name]`) but it needs to be converted to a string or a dict in order to add it as the message body. I would start by inspecting the column types from your document and how to properly serialize them.
> 
> Also, the last line should be `return str(resp)`.

Since `df` is a pandas dataframe, `ret = df[col_name]` is a pandas series. The data type of the column is string as follow:

```
column 1    |  column 2

someone   |   someday
```

**Comment by childish-sambino** [comment]
Yeah, so if it's a series of data, how do you want it to be serialized into the message body (i.e., comma-separated, tab-separated, or something else?). I don't think the lib itself should take on this responsibility. If you can serialize the series into a string and then use that as the message body that should work.
