### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Pyton-Projects** [twilio/twilio-python#567]
The Error Is Coming 
Error:
Traceback (most recent call last):
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\util\ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\util\ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.twilio.com', port=443): Max retries exceeded with url: /2010-04-01/Accounts/ACc75cedcab3b2cb2db0d21f0afb09aebf/Messages.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\projects\asdsdsd.py", line 5, in <module>
    c.messages.create(to='+918317050957',from_='+15046081138',body='This Is A Test messages!')
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\site-packages\twilio\rest\api\v2010\account\message\__init__.py", line 88, in create
    payload = self._version.create(method='POST', uri=self._uri, data=data )
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\site-packages\twilio\base\version.py", line 193, in create
    response = self.request(
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\site-packages\twilio\base\version.py", line 39, in request
    return self.domain.request(
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\site-packages\twilio\base\domain.py", line 38, in request
    return self.twilio.request(
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\site-packages\twilio\rest\__init__.py", line 129, in request
    return self.http_client.request(
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\site-packages\twilio\http\http_client.py", line 91, in request
    response = session.send(
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.twilio.com', port=443): Max retries exceeded with url: /2010-04-01/Accounts/ACc75cedcab3b2cb2db0d21f0afb09aebf/Messages.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))
Code:
from twilio.rest import Client
auccont_Id='account sid '
auth_token='auth_token'
c=Client(auccont_Id,auth_token)
c.messages.create(to='+91**********',from_='+1**********',body='This Is A Test messages!')
why the error is coming?? if you know please drop a comment (:

**Comment by shwetha-manvinkurke** [comment]
Hi @Pyton-Projects [this](https://support.twilio.com/hc/en-us/articles/360007853433-Troubleshooting-Certificate-Errors-from-the-Twilio-REST-API) might help you understand the issue better. If you need further help, I recommend reaching out to [support](https://support.twilio.com).
