### ISSUE TITLE
Edge = "roaming" does not work:

### ISSUE THREAD

**Issue by mangelozzi** [twilio/twilio-python#583]
### Issue Summary
If I understand the documentation correctly, one can specify a location with either 'region' or `edge`. `region` has been depreciated for the now preferred `edge`. The two represent the same location, just that `edge` is more verbose.

<https://www.twilio.com/docs/global-infrastructure/edge-locations/legacy-regions> says one can use the edge location `roaming`, this is beneficial because I am far from all the edge locations, and it is not apparent which one will have the lowest latency.

### Steps to Reproduce
client = Client(edge='roaming')

### Code Snippet
```python
    client = Client(TWILIO_ACCOUNT_SID, TWILIO_TOKEN , edge='roaming')
    message = client.messages.create(
        to=to,
        body=body,
        from_=MY_NUMBER
    )
```

### Exception/Log
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/michael/linkcube/src/core/notify/sms_twilio.py", line 39, in send_test_sms
    ok, note = send_sms(to=cleaned_to, body=body)
  File "/home/michael/linkcube/src/core/notify/sms_twilio.py", line 24, in send_sms
    message = client.messages.create(
  File "/home/michael/venv/linkcube/lib/python3.8/site-packages/twilio/rest/api/v2010/account/message/__init__.py", line 88, in create
    payload = self._version.create(method='POST', uri=self._uri, data=data, )
  File "/home/michael/venv/linkcube/lib/python3.8/site-packages/twilio/base/version.py", line 193, in create
    response = self.request(
  File "/home/michael/venv/linkcube/lib/python3.8/site-packages/twilio/base/version.py", line 39, in request
    return self.domain.request(
  File "/home/michael/venv/linkcube/lib/python3.8/site-packages/twilio/base/domain.py", line 38, in request
    return self.twilio.request(
  File "/home/michael/venv/linkcube/lib/python3.8/site-packages/twilio/rest/__init__.py", line 131, in request
    return self.http_client.request(
  File "/home/michael/venv/linkcube/lib/python3.8/site-packages/twilio/http/http_client.py", line 91, in request
    response = session.send(
  File "/home/michael/venv/linkcube/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/michael/venv/linkcube/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.roaming.us1.twilio.com', port=443): Max retries exceeded with url: /2010-04-01/Accounts/AC40b040c4be70db10d30db08a29fb631d/Messages.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f049c75a2e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

### Technical details:
* twilio-python version:  7.3.2
* python version: 3.8

### Note

I get the same result with:
```
client = Client(TWILIO_ACCOUNT_SID, TWILIO_TOKEN , region='gll')
```

**Comment by childish-sambino** [comment]
In order to properly debug this issue, please [file a support ticket](https://twilio.com/help/contact).
