### ISSUE TITLE
9.0.5: documentation no longer builds

### ISSUE THREAD

**Issue by kloczek** [twilio/twilio-python#790]
Looks like with latest 9.0.5 it is no longer possible to build documentation because some files are missing.
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v7.2.6
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid language code. Falling back to 'en' (English).
making output directory... done
WARNING: html_static_path entry 'source/_static' does not exist
WARNING: The pre-Sphinx 1.0 'intersphinx_mapping' format is deprecated and will be removed in Sphinx 8. Update to the current format as described in the documentation. Hint: "intersphinx_mapping = {'<name>': ('https://docs.python.org/', None)}".https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_mapping
loading intersphinx inventory from https://docs.python.org/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment: [new config] 0 added, 0 changed, 0 removed
reading sources...

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sphinx/cmd/build.py", line 298, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/lib/python3.10/site-packages/sphinx/application.py", line 355, in build
    self.builder.build_update()
  File "/usr/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 290, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 313, in build
    updated_docnames = set(self.read())
  File "/usr/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 423, in read
    raise SphinxError('root file %s not found' %
sphinx.errors.SphinxError: root file /home/tkloczko/rpmbuild/BUILD/twilio-python-9.0.5/docs/index.rst not found

Sphinx error:
root file /home/tkloczko/rpmbuild/BUILD/twilio-python-9.0.5/docs/index.rst not found
```

**Comment by tiwarishubham635** [comment]
Can you share some more context for reproducing the error?

**Comment by kloczek** [comment]
Just please try to clone git repo in which this file is missing.

**Comment by tiwarishubham635** [comment]
Are you sure you were able to do this in earlier versions? I see docs folder did not have this file earlier as well?

**Comment by tiwarishubham635** [comment]
So I see that it checks for index.rst which is the entrypoint. We do not have that in our repo. I can take a look on how to add it.

**Comment by tiwarishubham635** [comment]
Created an [internal ticket](https://twilio-engineering.atlassian.net/browse/DII-1450) for this to be picked up. +1s will help it move up. Thanks!

**Comment by tiwarishubham635** [comment]
Just a suggestion, can you try running [make docs](https://github.com/twilio/twilio-python/blob/main/Makefile#L38) command? We are using the same for verifying docs generation. Please check this once and let me know.

**Comment by kloczek** [comment]
So looks like autodoc support is not finished/broken in conf.py

**Comment by tiwarishubham635** [comment]
I think #807 will fix that issue
